config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: "sessions"}

  root to: 'home#index'

  get 'users/dashboard'
  get 'users/items_management'
  get 'users/collections_management'
  get 'users/collection_creation_form'
  get 'users/view_collection'
  get 'users/admin_page', to: 'users#admin_page'
  post 'users/submited/choice', to: 'users#manage'
  get 'users/admin_user_view', to: 'users#admin_user_view'
  get 'users/create_item'
  get 'users/view_item'

  post 'users/create/collection', to: 'users#create_collection'
  post 'users/edit/collection', to: 'users#edit_collection'
  post 'users/create_item', to: 'users#create_item'
  post 'users/edit/item', to: 'users#edit_item'

  get 'home/index'
  get 'home/collections/listing', to: 'home#collections_listing'
  get 'home/items/listing', to: 'home#items_listing'
  get 'home/view/item', to: 'home#view_item'
  get 'home/view_collection', to: 'home#view_collection'
  get 'change_language', to: 'home#change_language'

  post 'home/vote', to: 'home#vote'
  post 'home/comment', to: 'home#comment'

  post 'home/search_results', to: 'home#search_results'
  post 'home/search', to: 'home#search_results'
  get 'home/search', to: 'home#search_results'

  get 'ticket/new'
  post 'ticket/create', to: 'ticket#create'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/user.rb
class User < ApplicationRecord
  #has_one_attached :image
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :lockable, :timeoutable, :trackable, :omniauthable#,
         #:confirmable
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :valid_user

  def admin_page
    if valid_admin
      @users = User.unscoped.all
    end
  end

  def dashboard
    @items_count = Item.where(owner_id: current_user.id).count
    @collections_count = Collection.where(owner_id: current_user.id).count
  end


  def manage
    selected_user_ids = params[:user_ids]

    if params[:block]
      User.unscoped.where(id: selected_user_ids).update_all(status: "blocked")
      if selected_user_ids.include?(current_user.id.to_s)
        sign_out current_user
      end
    elsif params[:delete]
      Item.unscoped.where(owner_id: selected_user_ids).destroy_all
      Comment.unscoped.where(user_id: selected_user_ids).destroy_all
      collections = Collection.unscoped.where(owner_id: selected_user_ids)
      fields = CustomField.unscoped.where(collection_id: collections.pluck(:id))
      CustomFieldValue.unscoped.where(field_id: fields.pluck(:id)).destroy_all
      fields.destroy_all
      collections.destroy_all
      Vote.unscoped.where(user_id: selected_user_ids).destroy_all
      User.unscoped.where(id: selected_user_ids).destroy_all
    elsif params[:unblock]
      User.unscoped.where(id: selected_user_ids).update_all(status: "member")
    elsif params[:add_to_admin]
      User.unscoped.where(id: selected_user_ids).update_all(status: "admin")
    elsif params[:remove_from_admin]
      User.unscoped.where(id: selected_user_ids).update_all(status: "member")
    end

    flash[:notice] = "Action was successful!"
    redirect_to request.referer
  end

  def admin_user_view
    if valid_admin
      @user = User.find_by(id: params[:format])
      unless @user
        redirect_to users_admin_page_path
      end
    end
  end

  def collections_management
    @total = 0
    @collections = Collection.where(owner_id: current_user.id)
    if current_user.status == "admin"
      @collections = Collection.all
    end
    if @collections.nil?
      @collections = []
    else
      @collections.each do |collection|
        @total += 1
      end
    end
  end

  def create_collection
    @collection = Collection.create(name: params[:name], description: params[:description], category: params[:category], owner_id: current_user.id)
    @collection.save

    unless params[:field_name].nil?
      params[:field_name].each_with_index do |name, index|
        @fields = CustomField.create(field_name: name, field_type: params[:field_type][index], collection_id: @collection.id)
        @fields.save
      end
    end
    redirect_to users_collections_management_path
  end

  def view_collection
    @collection = Collection.find_by(id: params[:format])
    @fields = CustomField.where(collection_id: @collection.id)
  end

  def edit_collection
    @collection = Collection.find_by(id: params[:id])
    if @collection.owner_id.to_s == current_user.id.to_s || current_user.status == "admin"
      @fields = CustomField.where(collection_id: @collection.id)
      if params[:change]
        @collection.update(name: params[:name], description: params[:description], category: params[:category], updated_at: Time.now)
        @collection.save
        @fields.each do |field|
          field.destroy
        end
        unless params[:field_name].nil?
          params[:field_name].each_with_index do |name, index|
            @fields = CustomField.create(field_name: name, field_type: params[:field_type][index], collection_id: @collection.id)
            @fields.save
          end
        end
      elsif params[:delete]
        @collection.destroy
        @fields.each do |field|
          field.destroy
        end
      end
    end
    redirect_to users_collections_management_path
  end

  def items_management
    @items = Item.where(owner_id: current_user.id)
    if current_user.status == "admin"
      @items = Item.all
    end
    @collection_name = []
    @total = 0
    @items.each do |item|
      @total += 1
      if item.collection_id == 'NA'
        @collection_name << 'NA'
      else
        @collection_name << Collection.find_by(id: item.collection_id).name
      end
    end
  end

  def create_item
    @step = params[:next] ? '2' : params[:save] ? '3' : '1'
    if @step == '1'
      @collections = Collection.where(owner_id: current_user.id)
    elsif @step == '2'
      @collection_id = params[:collection_id]
      @fields = CustomField.where(collection_id: params[:collection_id])
    elsif @step == '3'
      tag_names = params[:tags]
      tag_names.split(',').each do |name|
        if Tag.find_by(name: name.strip).nil?
          tag = Tag.create(name: name.strip)
        else
          tag = Tag.find_by(name: name.strip)
          count = tag.count + 1
          tag.update(count: count)
        end
        tag.save
      end
      @item = Item.create(name: params[:name], tags: params[:tags], collection_id: params[:collection_id], owner_id: current_user.id)
      @item.save
      unless params[:field_value].nil?
        params[:field_value].each_with_index do |value, index|
          @fields_value = CustomFieldValue.create(value: value, field_id: params[:field_id][index], item_id: @item.id)
          @fields_value.save
        end
      end
      redirect_to users_items_management_path
    end
  end

  def view_item
    @item = Item.find_by(id: params[:format])
    if @item.collection_id != "NA"
      @fields_value = CustomFieldValue.where(item_id: @item.id)
      @fields = CustomField.where(collection_id: @item.collection_id)
    end
  end

  def edit_item
    @item = Item.find_by(id: params[:id])
    if @item.owner_id.to_s == current_user.id.to_s || current_user.status == "admin"
      @fields_value = CustomFieldValue.where(item_id: @item.id)
      if params[:update]
        tag_item_count(@item.tags, params[:tags])
        @item.update(name: params[:name], tags: params[:tags], updated_at: Time.now)
        @fields_value.each do |field|
          field.destroy
        end
        unless params[:field_value].nil?
          params[:field_value].each_with_index do |value, index|
            @fields_value = CustomFieldValue.create(value: value, field_id: params[:field_id][index], item_id: @item.id)
            @fields_value.save
          end
        end
        redirect_to request.referer
      elsif params[:delete]
        @item.destroy
        @fields_value.each do |field|
          field.destroy
        end
        redirect_to users_items_management_path
      end
    end
  end


  private
  def valid_admin
    if user_signed_in? && current_user.status == "admin"
      return true
    elsif user_signed_in? && current_user.status != "blocked"
      redirect_to users_dashboard_path
    else
      redirect_to root_path
    end
  end

  def valid_user
    if user_signed_in? && current_user.status != "blocked"
      return true
    else
      redirect_to root_path
    end
  end

  def tag_item_count(oldTags,newTags)
    oldTagArray = oldTags.split(',')
    newTagArray = newTags.split(',')
    oldTagArray.each do |oldTag|
      if !newTagArray.include?(oldTag.strip)
        oldTagCount = Tag.find_by(name: oldTag.strip).count
        oldTagCount -= 1
        Tag.find_by(name: oldTag).update(count: oldTagCount)
      end
    end
    newTagArray.each do |name|
      tag = Tag.find_or_create_by(name: name.strip)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/admin_page.html.erb
<%= form_tag(users_submited_choice_path, method: :post) do %>
<div class = 'grid grid-cols-1 gap-4'>
<div class="flex gap-4 justify-items-end">
  <%= submit_tag t("block"), name: 'block', class: "inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-red-600 hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500"%>

  <%= button_tag type: 'submit', name: 'delete', class: 'bg-red-600 hover:bg-red-700 border border-transparent text-white font-medium py-2 px-4 rounded-md', style: 'font-size:24px' do %>
    <i class="fa fa-trash-o" style="font-size:24px"></i>
  <% end %>

  <%= button_tag type: 'submit', name: 'unblock', class: "inline-flex justify-center items-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-green-600 hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-green-500" do %>
    <i class="fa fa-unlock" style="font-size:24px"></i>
  <% end %>

  <%= submit_tag t("promote"), name: 'add_to_admin', class: "inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-green-600 hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-green-500" %>

  <%= submit_tag t("demote"), name: 'remove_from_admin', class: "inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-red-600 hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500" %>
</div>

<div class="relative shadow-md sm:rounded-lg">
    <table class="text-sm text-left rtl:text-right text-gray-500 dark:text-gray-400">
        <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
            <tr>
                <th class="px-4 py-3">
                    <%= check_box_tag 'select_all', nil, false, id: 'selectAll' %>
                </th>
                <th class="hidden md:block md:table-cell px-4 py-3">
                    <%= t('id') %>
                </th>
                <th class="px-4 py-3">
                    <%= t('name') %>
                </th>
                <th class="px-4 py-4">
                <span class="hidden md:block">
                    <%= t('email') %>
                </span>
                </th>
                <th class="px-4 py-4">
                <span class="hidden lg:block">
                    <%= t('last_logged') %>
                </span>
                </th>
                <th class="px-4 py-4">
                <span class="hidden lg:block">
                    <%= t('joined_at') %>
                </span>
                </th>
                <th class="px-4 py-3">
                    <%= t('status') %>
                </th>
            </tr>
        </thead>
        <tbody>
        <% @users.each do |user| %>
            <tr class="odd:bg-white odd:dark:bg-gray-900 even:bg-gray-50 even:dark:bg-gray-800 border-b dark:border-gray-700">
                <th class="px-4 py-4">
                    <%= check_box_tag 'user_ids[]', user.id, false, class: 'input[type=checkbox]' %>
                </th>
                <td class="hidden md:table-cell md:block px-4 py-4">
                    <%= user.id %>
                </td>
                <td class="px-4 py-4">
                    <%= link_to user.name, users_admin_user_view_path(user.id), class: 'hover:underline hover:text-blue-600'%>
                    <div class = "flex md:hidden">
                        <%= user.email %>
                    </div>
                </td>
                <td class="px-4 py-4">
                <span class="hidden md:block">
                    <%= user.email %>
                </span>
                </td>
                <td class="px-4 py-4">
                <span class="hidden lg:block">
                    <%= user.current_sign_in_at %>
                </span>
                </td>
                <td class="px-4 py-4">
                <span class="hidden lg:block">
                    <%= user.created_at %>
                </span>
                </td>
                <td class="px-4 py-4">
                    <%= user.status %>
                </td>
            </tr>
        <% end %>
        </tbody>
    </table>
</div>
</div>
<% end %>

<script>
$("#selectAll").click(function() {
  $("input[type=checkbox]").prop("checked", $(this).prop("checked"));
});

$("input[type=checkbox]").click(function() {
  if (!$(this).prop("checked")) {
    $("#selectAll").prop("checked", false);
  }
});

jackHarnerSig();
</script>

app/views/users/admin_user_view.erb
<div class = 'bg-white dark:bg-gray-800 grid grid-cols-1 gap-4 rounded-lg p-4'>
<div class="flex flex-col gap-4 dark:text-white">
  <div class="flex justify-between">
    <span class="font-bold">
      <%= @user.name %>
    </span>
    <span class="text-gray-500 dark:text-white">
      <%= @user.email %>
    </span>
  </div>

  <dl class="grid grid-cols-2 gap-4 dark:text-white">
    <dt class="font-bold">
      <%= t('user_signed_in_at') %>
    </dt>
    <dd>
      <%= @user.current_sign_in_at %>
    </dd>

    <dt class="font-bold">
      <%= t('created_at') %>
    </dt>
    <dd>
      <%= @user.created_at %>
    </dd>

    <dt class="font-bold">
      <%= t('status') %>
    </dt>
    <dd>
      <%= @user.status %>
    </dd>

    <dt class="font-bold">
      <%= t('nationality') %>
    </dt>
    <dd>
      <%= @user.nationality %>
    </dd>

    <dt class="font-bold">
      <%= t('city') %>
    </dt>
    <dd>
      <%= @user.city %>
    </dd>
  </dl>
</div>
<%= form_tag(users_submited_choice_path, method: :post) do %>

<%= hidden_field_tag :user_ids, [@user.id] %>


<div class="flex gap-4 justify-items-end">
  <%= submit_tag 'Block', name: 'block', class: "inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-red-600 hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500"%>

  <%= button_tag type: 'submit', name: 'delete', class: 'bg-red-600 hover:bg-red-700 border border-transparent text-white font-medium py-2 px-4 rounded-md', style: 'font-size:24px' do %>
    <i class="fa fa-trash-o" style="font-size:24px"></i>
  <% end %>

  <%= button_tag type: 'submit', name: 'unblock', class: "inline-flex justify-center items-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-green-600 hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-green-500" do %>
    <i class="fa fa-unlock" style="font-size:24px"></i>
  <% end %>

  <%= submit_tag 'Promote', name: 'add_to_admin', class: "inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-green-600 hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-green-500" %>

  <%= submit_tag 'Demote', name: 'remove_from_admin', class: "inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-red-600 hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500" %>
</div>
<% end %>
</div>

app/views/users/collection_creation_form.html.erb
<div class = 'bg-white dark:bg-gray-800 p-4 mt-8 rounded-lg w-full h-full'>
<h1 class = "text-2xl b-7 text-gray-900 dark:text-white"><strong><%= t('collection_creation')%></strong></h1>

<%= form_tag users_create_collection_path, method: :post, html: { class: 'max-w-md mx-auto mt-4' } do%>
  
  <div class="grid md:grid-cols-2 md:gap-6">
    <div class="relative z-0 w-full mb-5 group">
      <%= text_field_tag :name, nil, class: "block py-2.5 px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer", placeholder: ' ', required: true %>
      <label for="floating_name" class="peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:start-0 rtl:peer-focus:translate-x-1/4 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6"><%= t('name') %></label>
    </div>
    <div class="relative z-0 w-full mb-5 group">
        <label for="categories" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white"><%= t('category') %>:</label>
        <select id="category" name='category' class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
          <option value="Books">Books</option>
          <option value="Signs">Signs</option>
          <option value="Silverware">Silverware</option>
          <option value="Art and Antiques">Art and Antiques</option>
          <option value="Stamps and Coins">Stamps and Coins</option>
          <option value="Toys and Games">Toys and Games</option>
          <option value="Music and Movies">Music and Movies</option>
          <option value="Sports Memorabilia">Sports Memorabilia</option>
          <option value="Vehicles">Vehicles</option>
          <option value="Other">Other</option>
        </select>
    </div>
    <div class="relative z-0 w-full mb-5">
      <%= text_area_tag :description, nil, class: "block py-2.5 px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer", placeholder: ' ', required: true, data: { markdown: true } %>
      <label for="description" class="peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:start-0 rtl:peer-focus:translate-x-1/4 rtl:peer-focus:left-auto peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6"><%= t('description') %></label>
    </div>
  </div>


  <div id="fields-container" class = 'grid grid-cols-1 md:grid-cols-2 gap-4 mt-4 text-sm text-gray-900 dark:text-white'>
    
  </div>

  <div class = 'grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4 mt-4'>
    <button type="button" class = 'text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800' id="add-button"><%= t('add_field') %></button>

    <%= submit_tag t('submit'), class: "text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" %>
  </div>

<% end %>
</div>




<script>
    let addButton = document.getElementById("add-button");
    addButton.addEventListener("click", function(){
      let container = document.getElementById("fields-container");
      let clone = document.createElement("div");
      clone.classList.add("field-container");

      let nameInput = document.createElement("input");
      nameInput.type = "text";
      nameInput.name = "field_name[]";
      nameInput.id = `field_name_${container.childElementCount}`;
      nameInput.className = "block py-2.5 px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer";

      let typeSelect = document.createElement("select");
      typeSelect.name = "field_type[]";
      typeSelect.id = `field_type_${container.childElementCount}`;
      typeSelect.className = 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500';
      typeSelect.onchange = function(){
        typeSelect.value = this.value;
      };

      let options = [
        { value: "integer", text: "Integer" },
        { value: "string", text: "String" },
        { value: "multiline_text", text: "Multiline text" },
        { value: "boolean_checkboxes", text: "Boolean checkboxes" },
        { value: "date", text: "Date" },
     ];

      options.forEach(option => {
        let optionElement = document.createElement("option");
        optionElement.value = option.value;
        optionElement.innerText = option.text;
        if (option.value === document.querySelector(`#field_type_${container.childElementCount - 1}`)?.value) {
          optionElement.selected = true;
        }

        typeSelect.appendChild(optionElement);
      });

      clone.appendChild(document.createElement("label")).innerText = "<%= t('field_name') %>: ";
      clone.appendChild(nameInput);

      clone.appendChild(document.createElement("label")).innerText = "<%= t('field_type') %>: ";
      clone.appendChild(typeSelect);

      container.appendChild(clone);
    });
  </script>

app/views/users/collections_management.html.erb
<div class = ' bg-white dark:bg-gray-800 p-4 mt-7 rounded w-full'>

<div class = 'flex justify-between dark:text-white'>

<%= t('collection_count') %> : <%= @total %>

<%= link_to t('create_new'), users_collection_creation_form_path, class: "px-5 py-2.5 text-sm font-medium text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 rounded-lg text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" %>

</div>
<div class="relative shadow-md sm:rounded-lg mt-7">
    <table class="text-sm text-left rtl:text-right text-gray-500 dark:text-gray-400 lg:w-full p-2">
        <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
            <tr>
                <th class="px-4 py-3">
                    <%= t('id') %>
                </th>
                <th class="px-4 py-3">
                    <%= t('name') %>
                </th>
                <th class="hidden md:table-cell md:block px-4 py-4">
                    <%= t('item_count') %>
                </th>
                <th class="px-4 py-4">
                    <%= t('action') %>
                </th>
            </tr>
        </thead>
        <tbody>
        <% @collections.each do |collection| %>
            <tr class="odd:bg-white odd:dark:bg-gray-900 even:bg-gray-50 even:dark:bg-gray-800 border-b dark:border-gray-700">
                <td class="px-4 py-4">
                    <%= collection.id %>
                </td>
                <td class="px-4 py-4">
                    <%= collection.name %>
                </td>
                <td class="hidden md:table-cell md:block px-4 py-4">
                    <%= collection.items_count %>
                </td>
                <td class="px-4 py-4">
                    <%= link_to t('edit'), users_view_collection_path(collection.id), class: 'px-5 py-2.5 text-sm font-medium text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 rounded-lg text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800'%>
                </td>
            </tr>
        <% end %>
        </tbody>
    </table>
</div>

app/views/users/items_management.html.erb
<div class = ' bg-white dark:bg-gray-800 p-4 mt-7 rounded w-full'>

<div class = 'flex justify-between dark:text-white'>

 <%= t('item_count') %> : <%= @total %>

<%= link_to t('create_new'), users_create_item_path, class: "px-5 py-2.5 text-sm font-medium text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 rounded-lg text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" %>

</div>
<div class="relative shadow-md sm:rounded-lg mt-7">
    <table class="text-sm text-left rtl:text-right text-gray-500 dark:text-gray-400 lg:w-full">
        <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
            <tr>
                <th class="px-4 py-3">
                     <%= t('id') %>
                </th>
                <th class="hidden md:table-cell md:block px-4 py-3">
                     <%= t('collection_name') %>
                </th>
                <th class="px-4 py-3">
                     <%= t('name') %>
                </th>
                <th class="hidden md:table-cell md:block px-4 py-4">
                     <%= t('tags') %>
                </th>
                <th class="px-4 py-4">
                     <%= t('action') %>
                </th>
            </tr>
        </thead>
        <tbody>
        <% @items.each_with_index do |item,index| %>
            <tr class="odd:bg-white odd:dark:bg-gray-900 even:bg-gray-50 even:dark:bg-gray-800 border-b dark:border-gray-700">
                <td class="px-4 py-4">
                    <%= item.id %>
                </td>
                <td class="hidden md:table-cell md:block px-4 py-4">
                    <%= @collection_name[index] %>
                </td>
                <td class="px-4 py-4">
                    <%= item.name %>
                </td>
                <td class="hidden md:table-cell md:block px-4 py-4">
                    <%= item.tags %>
                </td>
                <td class="px-4 py-4">
                    <%= link_to t('edit'), users_view_item_path(item.id), class: 'px-5 py-2.5 text-sm font-medium text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 rounded-lg text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800'%>
                </td>
            </tr>
        <% end %>
        </tbody>
    </table>
</div>