config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: "sessions"}

  root to: 'home#index'

  get 'users/dashboard'
  get 'users/items_management'
  get 'users/collections_management'
  get 'users/collection_creation_form'
  get 'users/view_collection'
  get 'users/admin_page', to: 'users#admin_page'
  post 'users/submited/choice', to: 'users#manage'
  get 'users/admin_user_view', to: 'users#admin_user_view'
  get 'users/create_item'
  get 'users/view_item'

  post 'users/create/collection', to: 'users#create_collection'
  post 'users/edit/collection', to: 'users#edit_collection'
  post 'users/create_item', to: 'users#create_item'
  post 'users/edit/item', to: 'users#edit_item'

  get 'home/index'
  get 'home/collections/listing', to: 'home#collections_listing'
  get 'home/items/listing', to: 'home#items_listing'
  get 'home/view/item', to: 'home#view_item'
  get 'home/view_collection', to: 'home#view_collection'
  get 'change_language', to: 'home#change_language'

  post 'home/vote', to: 'home#vote'
  post 'home/comment', to: 'home#comment'

  post 'home/search_results', to: 'home#search_results'
  post 'home/search', to: 'home#search_results'
  get 'home/search', to: 'home#search_results'

  get 'ticket/new'
  post 'ticket/create', to: 'ticket#create'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    session[:lang] ||= 'en'
    set_locale
    @tags = Tag.order(count: :desc).limit(5)
    @items = Item.order(created_at: :desc).limit(5)
    @collections = Collection.order(items_count: :desc).limit(5)
    @item_Owners = []
    @items.each do |item|
      @item_Owners << User.find_by(id: item.owner_id).name
    end
    @collection_Owners = []
    @collections.each do |collection|
      @collection_Owners << User.find_by(id: collection.owner_id).name
    end

  end

  def change_language
    session[:lang] = params[:lang]
    set_locale
    redirect_to request.referer
  end

  def items_listing
    @Items = Item.all
    @Owners = []
    @Items.each do |item|
      @Owners << User.find_by(id: item.owner_id).name
    end
  end

  def collections_listing
    @Collections = Collection.all
    @Owners = []
    @Collections.each do |collection|
      @Owners << User.find_by(id: collection.owner_id).name
    end
  end

  def view_item
    @item = Item.find_by(id: params[:format])
    if @item.collection_id != "NA"
      @collection_name = Collection.find_by(id: @item.collection_id).name
      @fields = CustomField.where(collection_id: @item.collection_id)
      @field_values = []
      @fields.each do |field|
        @field_values << CustomFieldValue.find_by(item_id: @item.id, field_id: field.id).value
      end
    else
      @collection_name = "NA"
    end
    @owner_name = User.find_by(id: @item.owner_id).name
    @likes = Vote.where(type_name: 'item', type_id: @item.id, action: 'like').count
    if @likes.nil?
      @likes = 0
    end

    @dislikes = Vote.where(type_name: 'item', type_id: @item.id, action: 'dislike').count
    if @dislikes.nil?
      @dislikes = 0
    end

    if user_signed_in?
      @vote = Vote.find_by(type_name: 'item', type_id: @item.id, user_id: current_user.id)
      if @vote.nil?
        @liked = 0
      elsif @vote.action == 'like'
        @liked = 1
      else
        @liked = 2
      end
    else
      @liked = 0
    end

    @comments = Comment.where(type_name: 'item', type_id: @item.id)
  end

  def view_collection
    @collection = Collection.find_by(id: params[:format])
    @items = Item.where(collection_id: @collection.id)
    @items_count = @items.count
    @fields = CustomField.where(collection_id: @collection.id)
    @owner_name = User.find_by(id: @collection.owner_id).name
    @likes = Vote.where(type_name: 'collection', type_id: @collection.id, action: 'like').count
    if @likes.nil?
      @likes = 0
    end

    @dislikes = Vote.where(type_name: 'collection', type_id: @collection.id, action: 'dislike').count
    if @dislikes.nil?
      @dislikes = 0
    end

    if user_signed_in?
      @vote = Vote.find_by(type_name: 'collection', type_id: @collection.id, user_id: current_user.id)
      if @vote.nil?
        @liked = 0
      elsif @vote.action == 'like'
        @liked = 1
      else
        @liked = 2
      end
    end

    @comments = Comment.where(type_name: 'collection', type_id: @collection.id)
  end

  def search_results
    @tags = Tag.order(count: :desc).limit(5)
    if params[:tag_search]
      tag = params[:format]
      @items = Item.where("tags LIKE ?", "%#{tag}%")
      @Owners = []
      @items.each do |item|
        @Owners << User.find_by(id: item.owner_id).name
      end
      @collections = []
    elsif params[:search]
      text = params[:search_string]
      @items = []
      @collections = []

      temp_items = Item.where("name LIKE ?", "%#{text}%")
      temp_items_tag = Item.where("tags LIKE ?", "%#{text}%")
      temp_collections = Collection.where("name LIKE ?", "%#{text}%")
      temp_collections_desc = Collection.where("description LIKE ?", "%#{text}%")
      temp_collections_cate = Collection.where("category LIKE ?", "%#{text}%")
      users = User.where("name LIKE ?", "%#{text}%")

      @comments = Comment.where("content LIKE ?", "%#{text}%")

      users.each do |user|
        if Item.where(owner_id: user.id)
          temp_items_owner = Item.where(owner_id: user.id)
          temp_items_owner.each do |item|
            @items << item
          end
        end
        if Collection.where(owner_id: user.id)
          temp_collections_owner = Collection.where(owner_id: user.id)
          temp_collections_owner.each do |collection|
            @collections << collection
          end
        end
      end
      temp_items.each do |item|
        @items << item
      end
      temp_items_tag.each do |item|
        @items << item
      end
      temp_collections.each do |collection|
        @collections << collection
      end
      temp_collections_desc.each do |collection|
        @collections << collection
      end
      temp_collections_cate.each do |collection|
        @collections << collection
      end

      @comments.each do |comment|
        if comment.type_name == "item"
          @items << Item.find_by(id: comment.type_id)
        elsif comment.type_name == "collection"
          @collections << Collection.find_by(id: comment.type_id)
        end
      end

      @Owners = []
      @items.each do |item|
        @Owners << User.find_by(id: item.owner_id).name
      end
      @Owners_collections = []
      @collections.each do |collection|
        @Owners_collections << User.find_by(id: collection.owner_id).name
      end
    end

  end

  def vote
    if valid_user
      @vote = Vote.find_by(type_name: params[:type], type_id: params[:type_id], user_id: current_user.id)
      if @vote.nil?
        @vote = Vote.create(type_name: params[:type], type_id: params[:type_id], action: params[:action_name], user_id: current_user.id)
      elsif @vote.action == params[:action_name]
        @vote.destroy
      else
        @vote.update(action: params[:action_name])
      end
      redirect_to request.referer
    else
      redirect_to new_user_session_path
    end
  end

  def comment
    if valid_user
      @comment = Comment.create(content: params[:comment], type_name: params[:type_name], type_id: params[:type_id], user_id: current_user.id, user_name: current_user.name)
      @comment.save

      redirect_to request.referer
    else
      redirect_to new_user_session_path
    end

  end

  private

  def valid_user
    if user_signed_in? && current_user.status != "blocked"
      return true
    else
      return false
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/collections_listing.html.erb
<div class="grid grid-cols-2 md:grid-cols-4 gap-4">

   <% @Collections.each_with_index do |collection,index| %>
    <div class = 'bg-white dark:bg-gray-800 p-4 text-center dark:text-white'>
        <div class="mx-auto w-full flex justify-center">
            <img class="mx-auto w-1/2 h-1/2 max-w-xs max-h-xs rounded-lg" src="<%= collection.image_url.nil? ? image_path('collection') : collection.image_url %>" alt="">
        </div>
        <br>
        <%=link_to collection.name, home_view_collection_path(collection.id), class: "text-black hover:text-blue-600 dark:hover:text-blue-600 font-bold py-2 px-4 rounded dark:text-white" %>
        <br>
        <%= @Owners[index] %>
    </div>
    <% end %>
</div>

app/views/home/index.html.erb
<div class = 'grid grid-cols-1'>
  <div class="flex items-center justify-center py-4 md:py-8 flex-wrap">
    <% if @tags.nil? %>
      <p>No Tags available</p>
    <% else %>
    <% @tags.each do |tag| %>
      <%= button_to tag.name, home_search_results_path(tag.name), name: 'tag_search', class: "text-gray-900 border border-white hover:text-blue-700 hover:border-blue-700 dark:border-blue-900 dark:bg-blue-900 dark:hover:border-blue-700 bg-white focus:ring-4 focus:outline-none focus:ring-gray-300 rounded-full text-base font-medium px-5 py-2.5 text-center me-3 mb-3 dark:text-white dark:focus:ring-gray-800" %>
    <% end %>
    <% end %>
  </div>

<div class="bg-white dark:bg-gray-800 dark:text-white p-8 rounded-lg flex justify-between items-center text-center rounded-lg">
  <div class="flex flex-col items-center">
    <svg class="w-8 h-8 text-gray-600" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6v6m0 0v6m0-6h6m-6 0H6"></path></svg>
    <div class="text-lg font-medium mt-2"><%= t('user_friendly') %></div>
    <div class="text-sm text-gray-500 dark:text-gray-400"><%= t('user_friendly_text') %></div>
  </div>
  <div class="flex flex-col items-center">
    <svg class="w-8 h-8 text-gray-600" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z"></path></svg>
    <div class="text-lg font-medium mt-2"><%= t('showcase') %></div>
    <div class="text-sm text-gray-500 dark:text-gray-400"><%= t('showcase_text') %></div>
  </div>
  <div class="flex flex-col items-center">
    <svg class="w-8 h-8 text-gray-600" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M14 2a3.963 3.963 0 0 0-1.4.267 6.439 6.439 0 0 1-1.331 6.638A4 4 0 1 0 14 2Zm1 9h-1.264A6.957 6.957 0 0 1 15 15v2a2.97 2.97 0 0 1-.184 1H19a1 1 0 0 0 1-1v-1a5.006 5.006 0 0 0-5-5ZM6.5 9a4.5 4.5 0 1 0 0-9 4.5 4.5 0 0 0 0 9ZM8 10H5a5.006 5.006 0 0 0-5 5v2a1 1 0 0 0 1 1h11a1 1 0 0 0 1-1v-2a5.006 5.006 0 0 0-5-5Z"/></svg>
    <div class="text-lg font-medium mt-2"><%= t('community') %></div>
    <div class="text-sm text-gray-500 dark:text-gray-400"><%= t('community_text') %></div>
  </div>
</div>

<div class="bg-white dark:bg-gray-800 grid grid-cols-5 gap-4 md:grid-cols-5 p-4 mt-7 rounded-t-lg" id="itemsGallery" >
  <div class="col-span-5 md:col-span-2">
    <label class="block text-lg font-medium text-gray-700 dark:text-white"><%= t('items') %></label>
  </div>
</div>
<div class="bg-white dark:bg-gray-800 grid grid-cols-2 gap-4 md:grid-cols-4 p-4 border border-black dark:border-gray-700" id = 'itemsGallery'>
    <% @items.each_with_index do |item,index| %>
    <div class = 'bg-white dark:bg-gray-800 p-4 text-center dark:text-white border border-black dark:border-gray-700'>
        <div class="mx-auto w-full flex justify-center">
            <img class="mx-auto w-1/2 h-1/2 max-w-xs max-h-xs rounded-lg" src="<%= item.image_url.nil? ? image_path('item') : item.image_url %>" alt="">
        </div>
        <br>
        <%=link_to item.name, home_view_item_path(item.id), class: "text-black hover:text-blue-600 dark:hover:text-blue-600 font-bold py-2 px-4 rounded dark:text-white" %>
        <br>
        <%= @item_Owners[index] %>
    </div>
    <% end %>
</div>
<div class="rtl:mr-3 bg-white dark:bg-gray-800 p-4 rounded-b-lg">
  <%= link_to home_items_listing_path, class: "text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center inline-flex items-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" do %>
    <%= t('see_all') %>
    <svg class="rtl:rotate-180 w-3.5 h-3.5 ms-2" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 10">
      <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 5h12m0 0L9 1m4 4L9 9"/>
    </svg>
  <% end %>
</div>


<div class="bg-white dark:bg-gray-800 grid grid-cols-5 gap-4 md:grid-cols-5 p-4 mt-7 rounded-t-lg" id="collectionsGallery">
  <div class="col-span-5 md:col-span-2">
    <label class="block text-lg font-medium text-gray-700 dark:text-white"><%= t('collections') %></label>
  </div>
</div>
<div class="bg-white dark:bg-gray-800 grid grid-cols-2 gap-4 md:grid-cols-4 p-4 border border-black dark:border-gray-700" id = 'collectionGallery'>
    <% @collections.each_with_index do |collection,index| %>
    <div class = 'bg-white dark:bg-gray-800 p-4 text-center dark:text-white border border-black dark:border-gray-700'>
        <div class="mx-auto w-full flex justify-center">
            <img class="mx-auto w-1/2 h-1/2 max-w-xs max-h-xs rounded-lg" src="<%= collection.image_url.nil? ? image_path('collection') : collection.image_url %>" alt="">
        </div>
        <br>
        <%=link_to collection.name, home_view_collection_path(collection.id), class: "text-black hover:text-blue-600 dark:hover:text-blue-600 font-bold py-2 px-4 rounded dark:text-white" %>
        <br>
        <%= @collection_Owners[index] %>
    </div>
    <% end %>
</div>
<div class="rtl:mr-3 bg-white dark:bg-gray-800 p-4 rounded-b-lg">
  <%= link_to home_collections_listing_path, class: 'text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center inline-flex items-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800' do %>
    <%= t('see_all') %>
    <svg class="rtl:rotate-180 w-3.5 h-3.5 ms-2" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 10">
      <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 5h12m0 0L9 1m4 4L9 9"/>
    </svg>
  <% end %>
</div>
<div>

app/views/home/items_listing.html.erb
<div class="grid grid-cols-2 md:grid-cols-4 gap-4">

   <% @Items.each_with_index do |item,index| %>
    <div class = 'bg-white dark:bg-gray-800 p-4 text-center dark:text-white'>
        <div class="mx-auto w-full flex justify-center">
            <img class="mx-auto w-1/2 h-1/2 max-w-xs max-h-xs rounded-lg" src="<%= item.image_url.nil? ? image_path('item') : item.image_url %>" alt="">
        </div>
        <br>
        <%=link_to item.name, home_view_item_path(item.id), class: "text-black hover:text-blue-600 dark:hover:text-blue-600 font-bold py-2 px-4 rounded dark:text-white" %>
        <br>
        <%= @Owners[index] %>
    </div>
    <% end %>
</div>

app/views/home/search_results.html.erb
<div class = 'grid grid-cols-1'> 

<div class="flex items-center justify-center py-4 md:py-8 flex-wrap">
    <% @tags.each do |tag| %>
      <%= button_to tag.name, home_search_results_path(tag.name), name: 'tag_search', class: "text-gray-900 border border-white hover:text-blue-700 hover:border-blue-700 dark:border-blue-900 dark:bg-blue-900 dark:hover:border-blue-700 bg-white focus:ring-4 focus:outline-none focus:ring-gray-300 rounded-full text-base font-medium px-5 py-2.5 text-center me-3 mb-3 dark:text-white dark:focus:ring-gray-800" %>
    <% end %>
</div>

<div class = 'bg-white dark:bg-gray-800 p-4 mt-7 rounded'>
<p class = "text-2xl text-gray-900 dark:text-white"><strong><%= t('items') %></strong></p>
<div class="grid grid-cols-2 md:grid-cols-4 gap-4">
    <% @items.each_with_index do |item,index| %>
        <div class = 'bg-white dark:bg-gray-800 p-4 text-center dark:text-white'>
            <div class="mx-auto w-full flex justify-center">
                <img class="mx-auto w-1/2 h-1/2 max-w-xs max-h-xs rounded-lg" src="<%= item.image_url.nil? ? image_path('item') : item.image_url %>" alt="">
            </div>
            <br>
            <%=link_to item.name, home_view_item_path(item.id), class: "text-black hover:text-blue-600 dark:hover:text-blue-600 font-bold py-2 px-4 rounded dark:text-white" %>
            <br>
            <%= @Owners[index] %>
        </div>
    <% end %>
</div>
</div>

<div class = 'bg-white dark:bg-gray-800 p-4 mt-7 rounded'>
<p class = "text-2xl text-gray-900 dark:text-white"><strong><%= t('collections') %></strong></p>
<div class="grid grid-cols-2 md:grid-cols-4 gap-4">
    <% @collections.each_with_index do |collection,index| %>
        <div class = 'bg-white dark:bg-gray-800 p-4 text-center dark:text-white'>
            <div class="mx-auto w-full flex justify-center">
                <img class="mx-auto w-1/2 h-1/2 max-w-xs max-h-xs rounded-lg" src="<%= collection.image_url.nil? ? image_path('collection') : collection.image_url %>" alt="">
            </div>
            <br>
            <%=link_to collection.name, home_view_collection_path(collection.id), class: "text-black hover:text-blue-600 dark:hover:text-blue-600 font-bold py-2 px-4 rounded dark:text-white" %>
            <br>
            <%= @Owners_collections[index] %>
        </div>
    <% end %>
</div>
</div>
</div>

app/views/home/view_collection.html.erb
<div class = 'z-10 grid grid-cols-1 bg-white w-full dark:bg-gray-800 p-4 border border-black dark:border-gray-700 dark:text-white rounded-lg border border-black'>
<h1 class = "text-2xl text-gray-900 dark:text-white"><strong><%= t('collection_view') %></strong></h1>
<div class="ml-0 mx-auto">
  <img class=" mx-auto w-20 h-20 max-w-xs max-h-xs rounded-lg" src="<%= @collection.image_url.nil? ? image_path('collection') : collection.image_url %>" alt="">
</div>
<div class=" z-20 grid grid-cols-2 gap-4 ">
  <div>
    <label for="collection-name" class="block text-lg font-medium text-gray-700 dark:text-white">
      <%= t("name") %> :
    </label>
    <p class = 'overflow-y-auto' id="collection-name"><%= @collection.name %></p>
  </div>

  <div>
    <label for="collection-id" class="block text-lg font-medium text-gray-700 dark:text-white">
      <%= t("id") %> :
    </label>
    <p class = 'overflow-y-auto' id="collection-id"><%= @collection.id %></p>
  </div>

  <div>
    <label for="collection-category" class="block text-lg font-medium text-gray-700 dark:text-white">
      <%= t("category") %> :
    </label>
    <p class = 'overflow-y-auto'><%= @collection.category %></p>
  </div>

  <div>
    <label for="owner-name" class="block text-lg font-medium text-gray-700 dark:text-white">
      <%= t("owner") %> :
    </label>
    <p class = 'overflow-y-auto' id="owner-name"><%= @owner_name %></p>
  </div>

  <div>
    <label for="description" class="block text-lg font-medium text-gray-700 dark:text-white">
      <%= t("description") %> :
    </label>
    <p class = 'overflow-y-auto' id="description"><%= markdown(@collection.description) %></p>
  </div>
  
  <% unless @fields.nil? %>
    <% @fields.each_with_index do |field,index| %>
    <div>
        <label for="field-values" class="block text-lg font-medium text-gray-700 dark:text-white">
        <%= field.field_name %>:
        </label>
        <p class = 'overflow-y-auto' id="field-type"><%= field.field_type %></p>
    </div>
    <% end %>
  <% end %>
  </div>

  <div class = 'mt-3'>
    <label for="owner-name" class="block text-lg font-medium text-gray-700 dark:text-white">
      <%= t("item_count") %> :
    </label>
    <p class = 'overflow-y-auto' id="owner-name"><%= @items_count %></p>
  </div>

  <% unless @items.nil? %>
    <div>
        <label for="name" class="block text-lg font-medium text-gray-700 dark:text-white">
        <%= t("name") %> : 
        </label>
        <% @items.each_with_index do |item,index| %>
          <p class = 'overflow-y-auto' id="item-name"><%= item.name %></p>
        <% end %>
    </div>
  <% end %>



<div class="flex justify-start gap-4 mt-7" >
  <%= form_tag home_vote_path, method: :post, html: { class: 'hover:bg-blue-700 w-1/2' } do%>
    <%= hidden_field_tag :type, 'collection' %>
    <%= hidden_field_tag :type_id, @collection.id %>
    <%= hidden_field_tag :action_name, 'like' %>

    <% if @liked == 1 %>
      <%= submit_tag t("like"), class: "text-blue-700 border border-blue-700 bg-blue-700 text-white focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm p-2.5 text-center inline-flex collections-center me-2 dark:border-blue-500 dark:text-blue-500 dark:hover:text-white dark:focus:ring-blue-800 dark:hover:bg-blue-500" %>
    <% else %>
      <%= submit_tag t("like"), class: "text-blue-700 border border-blue-700 hover:bg-blue-700 hover:text-white focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm p-2.5 text-center inline-flex collections-center me-2 dark:border-blue-500 dark:text-blue-500 dark:hover:text-white dark:focus:ring-blue-800 dark:hover:bg-blue-500" %>
    <% end %>
    <span id="like-counter" class="ml-2 text-sm"><%= @likes %></span>
  <% end %>
  <%= form_tag home_vote_path, method: :post, html: { class: 'hover:bg-blue-700 w-1/2' } do%>
    <%= hidden_field_tag :type, 'collection' %>
    <%= hidden_field_tag :type_id, @collection.id %>
    <%= hidden_field_tag :action_name, 'dislike' %>

    <% if @liked == 2 %>
      <%= submit_tag t("dislike"), class: "text-blue-700 border border-blue-700 bg-blue-700 text-white focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm p-2.5 text-center inline-flex collections-center me-2 dark:border-blue-500 dark:text-blue-500 dark:hover:text-white dark:focus:ring-blue-800 dark:hover:bg-blue-500" %>
    <% else %>
      <%= submit_tag t("dislike"), class: "text-blue-700 border border-blue-700 hover:bg-blue-700 hover:text-white focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm p-2.5 text-center inline-flex collections-center me-2 dark:border-blue-500 dark:text-blue-500 dark:hover:text-white dark:focus:ring-blue-800 dark:hover:bg-blue-500" %>
    <% end %>
    <span id="like-counter" class="ml-2 text-sm"><%= @dislikes %></span>
  <% end %>
</div>

<div class = 'mt-7'>
<%= form_tag home_comment_path, method: :post do%>
    <%= hidden_field_tag :type_name, 'collection' %>
    <%= hidden_field_tag :type_id, @collection.id %>
    
   <div class="w-full mb-4 border border-gray-200 rounded-lg bg-gray-50 dark:bg-gray-700 dark:border-gray-600">
       <div class="px-4 py-2 bg-white rounded-t-lg dark:bg-gray-800">
           <label for="comment" class="sr-only">Your comment</label>
           <textarea id="comment" name ="comment" rows="4" class="w-full px-0 text-sm text-gray-900 bg-white border-0 dark:bg-gray-800 focus:ring-0 dark:text-white dark:placeholder-gray-400" placeholder="Write a comment..." required ></textarea>
       </div>
       <div class="flex collections-center justify-between px-3 py-2 border-t dark:border-gray-600">
           <button type="submit" class="inline-flex collections-center py-2.5 px-4 text-xs font-medium text-center text-white bg-blue-700 rounded-lg focus:ring-4 focus:ring-blue-200 dark:focus:ring-blue-900 hover:bg-blue-800">
               Post comment
           </button>
       </div>
   </div>
<% end %>
</div>
<% unless @comments.nil? %>
    <% @comments.each do |comment| %>
    <div class = 'bg-white dark:bg-gray-800 p-4 mt-7 border border-black dark:border-gray-700 dark:text-white'>
        <p>User: <%= comment.user_name %></p>
        <p class = 'overflow-y-auto mt-2'><%= comment.content %></p>
    </div>
    <% end %>
<% end %>
</div>