config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: "sessions"}

  root to: 'home#index'

  get 'users/dashboard'
  get 'users/items_management'
  get 'users/collections_management'
  get 'users/collection_creation_form'
  get 'users/view_collection'
  get 'users/admin_page', to: 'users#admin_page'
  post 'users/submited/choice', to: 'users#manage'
  get 'users/admin_user_view', to: 'users#admin_user_view'
  get 'users/create_item'
  get 'users/view_item'

  post 'users/create/collection', to: 'users#create_collection'
  post 'users/edit/collection', to: 'users#edit_collection'
  post 'users/create_item', to: 'users#create_item'
  post 'users/edit/item', to: 'users#edit_item'

  get 'home/index'
  get 'home/collections/listing', to: 'home#collections_listing'
  get 'home/items/listing', to: 'home#items_listing'
  get 'home/view/item', to: 'home#view_item'
  get 'home/view_collection', to: 'home#view_collection'
  get 'change_language', to: 'home#change_language'

  post 'home/vote', to: 'home#vote'
  post 'home/comment', to: 'home#comment'

  post 'home/search_results', to: 'home#search_results'
  post 'home/search', to: 'home#search_results'
  get 'home/search', to: 'home#search_results'

  get 'ticket/new'
  post 'ticket/create', to: 'ticket#create'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/ticket_controller.rb
require 'jira-ruby'
class TicketController < ApplicationController
  def new
    @collections = Collection.all
  end

  def create
    client = JiraClient.new
    summary = params[:summary]
    priority = params[:priority]
    collection_name = params[:collection_name]  # Assuming collection might be optional
    link = request.referer
    current_user_email = current_user.email  # Assuming Devise for user authentication

    client.create_issue(summary, priority, collection_name, link, current_user_email, current_user.name)
  end


  private

  def ticket_params
    params.require(:ticket).permit(:summary, :priority, :collection_name)
  end

  # def create_jira_ticket(ticket)
  #   issue = client.Issue.build
  #   issue.save({
  #     'fields' => {
  #       'summary'     => ticket.summary,
  #       'description' => "Reported by: #{ticket.reported}\nCollection: #{ticket.collection}\nLink: #{ticket.link}",
  #       'project'     => { 'key' => 'YOUR_PROJECT_KEY' },
  #       'issuetype'   => { 'name' => 'Task' },
  #       'priority'    => { 'name' => ticket.priority },
  #       'assignee'    => { 'name' => ticket.reported },
  #       'status'      => { 'name' => 'Open' }
  #     }
  #   })
  # end
end

app/helpers/ticket_helper.rb
module TicketHelper
end

app/views/ticket/new.html.erb
<div class = 'bg-white dark:bg-gray-800 p-4 mt-8 rounded-lg w-full'>
  <h1 class = "text-2xl text-gray-900 dark:text-white"><strong><%= t('ticket_creation') %></strong></h1>

  <%= form_tag ticket_create_path, method: :post, html: { class: 'max-w-md mx-auto mt-4' } do%>
  
      <%#= hidden_field_tag :collection_id, @collection_id %>

      <div class="relative z-0 w-full mb-5 group">
        <%= text_field_tag :summary, nil, class: "block py-2.5 px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer", placeholder: ' ', required: true %>
        <label for="floating_summary" class="peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:start-0 rtl:peer-focus:translate-x-1/4 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6"><%= t('summary') %></label>
      </div>
      
      <div class="relative z-0 w-full mb-5">
        <label for="collection" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white text-2xl"><%= t('collections') %>:</label>
        <select id="collection" name='collection_name' class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
          <option value="NA">None</option>
          <% @collections.each do |collection| %>
            <option value="<%= collection.name %>"><%= collection.name %></option>
          <% end %>
        </select>
      </div>

      <div class="relative z-0 w-full mb-5">
        <label for="priority" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white text-2xl"><%= t('priority') %>:</label>
        <select id="priority" name='priority' class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
          <option value="Low">Low</option>
          <option value="Average">Average</option>
          <option value="High">High</option>
        </select>
      </div>

      <%= submit_tag "Save", name: 'save', class: "text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" %>
  <% end %>
</div>